In [1]:
import scipy
import sklearn
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import tree
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression, LinearRegression , BayesianRidge , ARDRegression
from sklearn import model_selection, preprocessing, feature_selection, ensemble, linear_model, metrics, decomposition

In [2]:
dtf = pd.read_csv('Downloads\Compressed\Phishing_Attack.csv')
dtf.head()

id  NumDots  SubdomainLevel  PathLevel  UrlLength  NumDash  \
0   1        3               1          5         72        0   
1   2        3               1          3        144        0   
2   3        3               1          2         58        0   
3   4        3               1          6         79        1   
4   5        3               0          4         46        0   

   NumDashInHostname  AtSymbol  TildeSymbol  NumUnderscore  ...  \
0                  0         0            0              0  ...   
1                  0         0            0              2  ...   
2                  0         0            0              0  ...   
3                  0         0            0              0  ...   
4                  0         0            0              0  ...   

   IframeOrFrame  MissingTitle  ImagesOnlyInForm  SubdomainLevelRT  \
0              0             0                 1                 1   
1              0             0                 0                 1   
2              0             0                 0                 1   
3              0             0                 0                 1   
4              1             0                 0                 1   

   UrlLengthRT  PctExtResourceUrlsRT  AbnormalExtFormActionR  \
0            0                     1                       1   
1           -1                     1                       1   
2            0                    -1                       1   
3           -1                     1                       1   
4            1                    -1                       0   

   ExtMetaScriptLinkRT  PctExtNullSelfRedirectHyperlinksRT  CLASS_LABEL  
0                   -1                                   1            1  
1                    1                                   1            1  
2                   -1                                   0            1  
3                    1                                  -1            1  
4                   -1                                  -1            1  

[5 rows x 50 columns]

In [3]:
X = dtf.drop('CLASS_LABEL', axis=1)
y = dtf['CLASS_LABEL']

# Train and Test Split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Linear Regression

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)
print('Training Accuracy : {:.2f}'.format(lr.score(X_train, y_train)))
print('Training Accuracy : {:.2f}'.format(lr.score(X_test, y_test)))

Training Accuracy : 0.87
Training Accuracy : 0.86


# Logistic Regression

In [6]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
pred = logreg.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(logreg.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(logreg.score(X_test, y_test)))

[[1224   13]
 [  12 1251]]
Training Accuracy : 0.99
Testing Accuracy : 0.99


# Bayesian Ridge

In [7]:
br = BayesianRidge()
br.fit(X_train, y_train)
print('Training Accuracy : {:.2f}'.format(br.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(br.score(X_test, y_test)))

Training Accuracy : 0.87
Testing Accuracy : 0.86


# Automatic Relevance Determination Regression (ARD)

In [8]:
ardr = ARDRegression(threshold_lambda=1e5)
ardr.fit(X_train, y_train)
print('Training Accuracy : {:.2f}'.format(ardr.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(ardr.score(X_test, y_test)))

Training Accuracy : 0.87
Testing Accuracy : 0.86


# Decision Tree

In [9]:
dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred = dt.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(dt.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(dt.score(X_test, y_test)))

[[1237    0]
 [   0 1263]]
Training Accuracy : 1.00
Testing Accuracy : 1.00


# Rendom Forest

In [10]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(rfc.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(rfc.score(X_test, y_test)))

[[1237    0]
 [   0 1263]]
Training Accuracy : 1.00
Testing Accuracy : 1.00


# SGD Classifier

In [11]:
sgd = SGDClassifier()
sgd.fit(X_train, y_train)
pred = sgd.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(sgd.score(X_train, y_train)))
print('Testing Accuracy : {:.2f}'.format(sgd.score(X_test, y_test)))

[[1218   19]
 [   0 1263]]
Training Accuracy : 0.99
Testing Accuracy : 0.99


# KNN

In [12]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(knn.score(X_train, y_train)))
print('Training Accuracy : {:.2f}'.format(knn.score(X_test, y_test)))

[[1209   28]
 [  45 1218]]
Training Accuracy : 0.98
Training Accuracy : 0.97


# Linear Discriminant Analysis

In [13]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
pred = lda.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(lda.score(X_train, y_train)))
print('Training Accuracy : {:.2f}'.format(lda.score(X_test, y_test)))

[[1224   13]
 [   8 1255]]
Training Accuracy : 0.99
Training Accuracy : 0.99


# Naive Bayes

In [14]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
pred = gnb.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(gnb.score(X_train, y_train)))
print('Training Accuracy : {:.2f}'.format(gnb.score(X_test, y_test)))

[[1198   39]
 [ 306  957]]
Training Accuracy : 0.86
Training Accuracy : 0.86


# SVC

In [15]:
svm = SVC()
svm.fit(X_train, y_train)
pred = svm.predict(X_test)
print(confusion_matrix(y_test, pred))
print('Training Accuracy : {:.2f}'.format(svm.score(X_train, y_train)))
print('Training Accuracy : {:.2f}'.format(svm.score(X_test, y_test)))

[[1232    5]
 [   6 1257]]
Training Accuracy : 1.00
Training Accuracy : 1.00
